// GENERATED by tools/sdk-codegen - DO NOT EDIT.
// Per-pack client for game-narrative on top of @kitefrost/core (PPI-3).

import { KiteFrostCore } from '@kitefrost/core';
import type { KiteFrostCoreConfig } from '@kitefrost/core';
import { CharactersResource, ContinuityResource, DialogueResource, FactionsResource, FeedbackResource, ItemsResource, LocationsResource, LoreBibleResource, ScenesResource, SeedsResource, SessionsResource, StoryArcsResource } from './resources.js';
import { PACK_SLUG, SDK_VERSION } from './version.js';

export * from './resources.js';
export { PACK_SLUG, SDK_VERSION } from './version.js';
export { KiteFrostCore } from '@kitefrost/core';
export type { KiteFrostCoreConfig } from '@kitefrost/core';

/**
 * Game Narrative pack client. Wraps a single shared KiteFrostCore so
 * multiple per-pack clients can share one auth provider / connection pool.
 */
export class GameNarrativeClient {
  readonly core: KiteFrostCore;
  readonly characters: CharactersResource;
  readonly continuity: ContinuityResource;
  readonly dialogue: DialogueResource;
  readonly factions: FactionsResource;
  readonly feedback: FeedbackResource;
  readonly items: ItemsResource;
  readonly locations: LocationsResource;
  readonly lore_bible: LoreBibleResource;
  readonly scenes: ScenesResource;
  readonly seeds: SeedsResource;
  readonly sessions: SessionsResource;
  readonly story_arcs: StoryArcsResource;

  constructor(config: KiteFrostCoreConfig | KiteFrostCore) {
    this.core = config instanceof KiteFrostCore ? config : new KiteFrostCore({
      ...config,
      userAgent: config.userAgent ?? `kitefrost-${PACK_SLUG}/${SDK_VERSION}`,
    });
    this.characters = new CharactersResource(this.core.http);
    this.continuity = new ContinuityResource(this.core.http);
    this.dialogue = new DialogueResource(this.core.http);
    this.factions = new FactionsResource(this.core.http);
    this.feedback = new FeedbackResource(this.core.http);
    this.items = new ItemsResource(this.core.http);
    this.locations = new LocationsResource(this.core.http);
    this.lore_bible = new LoreBibleResource(this.core.http);
    this.scenes = new ScenesResource(this.core.http);
    this.seeds = new SeedsResource(this.core.http);
    this.sessions = new SessionsResource(this.core.http);
    this.story_arcs = new StoryArcsResource(this.core.http);
  }
}
