// GENERATED by tools/sdk-codegen - DO NOT EDIT.
// Pack-specific resource layer on top of @kitefrost/core (PPI-3).
// Regenerate deterministically from the stripped per-pack OpenAPI spec.

import type { HttpClient } from '@kitefrost/core';

abstract class BaseResource {
  constructor(protected readonly http: HttpClient) {}
}

/** characters - pack-specific resource. */
export class CharactersResource extends BaseResource {
  audit_cast<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/audit`);
  }
  batch_create_characters<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/batch`, body);
  }
  batch_generate<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/batch/generate`, body);
  }
  create_characters<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters`, body);
  }
  delete_characters<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(entity_id)}`);
  }
  export_character<T = unknown>(project_id: string, character_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(character_id)}/export`, body);
  }
  generate_dialogue<T = unknown>(project_id: string, character_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(character_id)}/generate`, body);
  }
  get_characters<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(entity_id)}`);
  }
  list_characters<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters`, params);
  }
  refine_character<T = unknown>(project_id: string, character_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(character_id)}/refine`, body);
  }
  synthesize_character_voice<T = unknown>(project_id: string, character_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(character_id)}/voice`, body);
  }
  update_characters<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/characters/${encodeURIComponent(entity_id)}`, body);
  }
}

/** continuity - pack-specific resource. */
export class ContinuityResource extends BaseResource {
  audit_files<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/continuity/audit-files`, body);
  }
  check_continuity<T = unknown>(project_id: string): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/continuity/check`);
  }
}

/** dialogue - pack-specific resource. */
export class DialogueResource extends BaseResource {
  create_graph<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues`, body);
  }
  create_node<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/nodes`, body);
  }
  create_variable<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/narrative-variables`, body);
  }
  delete_graph<T = unknown>(project_id: string, graph_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}`);
  }
  delete_node<T = unknown>(project_id: string, node_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogue-nodes/${encodeURIComponent(node_id)}`);
  }
  delete_variable<T = unknown>(project_id: string, variable_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/narrative-variables/${encodeURIComponent(variable_id)}`);
  }
  export_dialogue_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/export`, body);
  }
  generate_dialogue_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/generate`, body);
  }
  get_graph<T = unknown>(project_id: string, graph_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}`);
  }
  get_node<T = unknown>(project_id: string, node_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogue-nodes/${encodeURIComponent(node_id)}`);
  }
  get_variable<T = unknown>(project_id: string, variable_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/narrative-variables/${encodeURIComponent(variable_id)}`);
  }
  import_dialogue_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/import`, body);
  }
  list_graphs<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues`);
  }
  list_nodes<T = unknown>(project_id: string, graph_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/nodes`);
  }
  list_variables<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/narrative-variables`);
  }
  patch_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}`, body);
  }
  patch_node<T = unknown>(project_id: string, node_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogue-nodes/${encodeURIComponent(node_id)}`, body);
  }
  patch_variable<T = unknown>(project_id: string, variable_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/narrative-variables/${encodeURIComponent(variable_id)}`, body);
  }
  refine_dialogue_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/refine`, body);
  }
  simulate_dialogue_graph<T = unknown>(project_id: string, graph_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/simulate`, body);
  }
  validate_dialogue_graph<T = unknown>(project_id: string, graph_id: string): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/dialogues/${encodeURIComponent(graph_id)}/validate`);
  }
}

/** factions - pack-specific resource. */
export class FactionsResource extends BaseResource {
  create_factions<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions`, body);
  }
  delete_factions<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(entity_id)}`);
  }
  export_faction<T = unknown>(project_id: string, faction_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(faction_id)}/export`, body);
  }
  generate_faction<T = unknown>(project_id: string, faction_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(faction_id)}/generate`, body);
  }
  get_factions<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(entity_id)}`);
  }
  list_factions<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions`, params);
  }
  refine_faction<T = unknown>(project_id: string, faction_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(faction_id)}/refine`, body);
  }
  update_factions<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/factions/${encodeURIComponent(entity_id)}`, body);
  }
}

/** feedback - pack-specific resource. */
export class FeedbackResource extends BaseResource {
  admin_list_feedback_attachments<T = unknown>(feedback_id: string): Promise<T> {
    return this.http.get<T>(`/v1/feedback/${encodeURIComponent(feedback_id)}/attachments`);
  }
  feedback_envelope_schema<T = unknown>(): Promise<T> {
    return this.http.get<T>(`/v1/feedback/schema.json`);
  }
  lookup_feedback<T = unknown>(feedback_id: string): Promise<T> {
    return this.http.get<T>(`/v1/feedback/${encodeURIComponent(feedback_id)}`);
  }
  request_attachment_upload_url<T = unknown>(body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/feedback/attachments/upload-url`, body);
  }
  submit_feedback_envelope<T = unknown>(): Promise<T> {
    return this.http.post<T>(`/v1/feedback`);
  }
}

/** items - pack-specific resource. */
export class ItemsResource extends BaseResource {
  create_items<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items`, body);
  }
  delete_items<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(entity_id)}`);
  }
  export_item<T = unknown>(project_id: string, item_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(item_id)}/export`, body);
  }
  generate_item<T = unknown>(project_id: string, item_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(item_id)}/generate`, body);
  }
  get_items<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(entity_id)}`);
  }
  list_items<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items`, params);
  }
  refine_item<T = unknown>(project_id: string, item_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(item_id)}/refine`, body);
  }
  update_items<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/items/${encodeURIComponent(entity_id)}`, body);
  }
}

/** locations - pack-specific resource. */
export class LocationsResource extends BaseResource {
  create_locations<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations`, body);
  }
  delete_locations<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(entity_id)}`);
  }
  export_location<T = unknown>(project_id: string, location_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(location_id)}/export`, body);
  }
  generate_location<T = unknown>(project_id: string, location_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(location_id)}/generate`, body);
  }
  get_locations<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(entity_id)}`);
  }
  list_locations<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations`, params);
  }
  refine_location<T = unknown>(project_id: string, location_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(location_id)}/refine`, body);
  }
  update_locations<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/locations/${encodeURIComponent(entity_id)}`, body);
  }
}

/** lore-bible - pack-specific resource. */
export class LoreBibleResource extends BaseResource {
  generate_lore_bible<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/lore-bible/generate`);
  }
}

/** scenes - pack-specific resource. */
export class ScenesResource extends BaseResource {
  create_scene<T = unknown>(project_id: string): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes`);
  }
  delete_scene<T = unknown>(project_id: string, session_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}`);
  }
  export_scene<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}/export`, body);
  }
  generate_scene<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}/generate`, body);
  }
  get_scene<T = unknown>(project_id: string, session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}`);
  }
  patch_scene<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}`, body);
  }
  refine_scene<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/scenes/${encodeURIComponent(session_id)}/refine`, body);
  }
}

/** seeds - pack-specific resource. */
export class SeedsResource extends BaseResource {
  batch_reject_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/batch/reject`, body);
  }
  batch_validate_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/batch/validate`, body);
  }
  delete_seed<T = unknown>(project_id: string, seed_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`);
  }
  generate_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/generate`, body);
  }
  get_seed<T = unknown>(project_id: string, seed_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`);
  }
  list_seeds<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds`, params);
  }
  patch_seed<T = unknown>(project_id: string, seed_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`, body);
  }
  promote_seed<T = unknown>(project_id: string, seed_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}/promote`, body);
  }
}

/** sessions - pack-specific resource. */
export class SessionsResource extends BaseResource {
  create_snapshot<T = unknown>(session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/sessions/${encodeURIComponent(session_id)}/snapshot`, body);
  }
  get_session_status<T = unknown>(session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/sessions/${encodeURIComponent(session_id)}/status`);
  }
  hitl_respond<T = unknown>(session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/sessions/${encodeURIComponent(session_id)}/respond`, body);
  }
  stream_session_events<T = unknown>(session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/sessions/${encodeURIComponent(session_id)}/stream`);
  }
}

/** story-arcs - pack-specific resource. */
export class StoryArcsResource extends BaseResource {
  create_story_arc<T = unknown>(project_id: string): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs`);
  }
  delete_story_arc<T = unknown>(project_id: string, quest_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}`);
  }
  export_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}/export`, body);
  }
  generate_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}/generate`, body);
  }
  get_quest<T = unknown>(project_id: string, quest_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}`);
  }
  patch_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}`, body);
  }
  refine_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/game-narrative/story-arcs/${encodeURIComponent(quest_id)}/refine`, body);
  }
}
