// GENERATED by tools/sdk-codegen - DO NOT EDIT.
// Per-pack client for ttrpg-gm on top of @kitefrost/core (PPI-3).

import { KiteFrostCore } from '@kitefrost/core';
import type { KiteFrostCoreConfig } from '@kitefrost/core';
import { FactionsResource, FeedbackResource, ItemsResource, LocationsResource, NpcsResource, PlacesResource, PlayersResource, SeedsResource, SessionsResource, TtrpgResource } from './resources.js';
import { PACK_SLUG, SDK_VERSION } from './version.js';

export * from './resources.js';
export { PACK_SLUG, SDK_VERSION } from './version.js';
export { KiteFrostCore } from '@kitefrost/core';
export type { KiteFrostCoreConfig } from '@kitefrost/core';

/**
 * Ttrpg Gm pack client. Wraps a single shared KiteFrostCore so
 * multiple per-pack clients can share one auth provider / connection pool.
 */
export class TtrpgGmClient {
  readonly core: KiteFrostCore;
  readonly factions: FactionsResource;
  readonly feedback: FeedbackResource;
  readonly items: ItemsResource;
  readonly locations: LocationsResource;
  readonly npcs: NpcsResource;
  readonly places: PlacesResource;
  readonly players: PlayersResource;
  readonly seeds: SeedsResource;
  readonly sessions: SessionsResource;
  readonly ttrpg: TtrpgResource;

  constructor(config: KiteFrostCoreConfig | KiteFrostCore) {
    this.core = config instanceof KiteFrostCore ? config : new KiteFrostCore({
      ...config,
      userAgent: config.userAgent ?? `kitefrost-${PACK_SLUG}/${SDK_VERSION}`,
    });
    this.factions = new FactionsResource(this.core.http);
    this.feedback = new FeedbackResource(this.core.http);
    this.items = new ItemsResource(this.core.http);
    this.locations = new LocationsResource(this.core.http);
    this.npcs = new NpcsResource(this.core.http);
    this.places = new PlacesResource(this.core.http);
    this.players = new PlayersResource(this.core.http);
    this.seeds = new SeedsResource(this.core.http);
    this.sessions = new SessionsResource(this.core.http);
    this.ttrpg = new TtrpgResource(this.core.http);
  }
}
