// GENERATED by tools/sdk-codegen - DO NOT EDIT.
// Pack-specific resource layer on top of @kitefrost/core (PPI-3).
// Regenerate deterministically from the stripped per-pack OpenAPI spec.

import type { HttpClient } from '@kitefrost/core';

abstract class BaseResource {
  constructor(protected readonly http: HttpClient) {}
}

/** factions - pack-specific resource. */
export class FactionsResource extends BaseResource {
  create_factions<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/factions`, body);
  }
  delete_factions<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/factions/${encodeURIComponent(entity_id)}`);
  }
  get_factions<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/factions/${encodeURIComponent(entity_id)}`);
  }
  list_factions<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/factions`, params);
  }
  update_factions<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/factions/${encodeURIComponent(entity_id)}`, body);
  }
}

/** feedback - pack-specific resource. */
export class FeedbackResource extends BaseResource {
  admin_list_feedback_attachments<T = unknown>(feedback_id: string): Promise<T> {
    return this.http.get<T>(`/v1/feedback/${encodeURIComponent(feedback_id)}/attachments`);
  }
  feedback_envelope_schema<T = unknown>(): Promise<T> {
    return this.http.get<T>(`/v1/feedback/schema.json`);
  }
  lookup_feedback<T = unknown>(feedback_id: string): Promise<T> {
    return this.http.get<T>(`/v1/feedback/${encodeURIComponent(feedback_id)}`);
  }
  request_attachment_upload_url<T = unknown>(body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/feedback/attachments/upload-url`, body);
  }
  submit_feedback_envelope<T = unknown>(): Promise<T> {
    return this.http.post<T>(`/v1/feedback`);
  }
}

/** items - pack-specific resource. */
export class ItemsResource extends BaseResource {
  create_items<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/items`, body);
  }
  delete_items<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/items/${encodeURIComponent(entity_id)}`);
  }
  get_items<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/items/${encodeURIComponent(entity_id)}`);
  }
  list_items<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/items`, params);
  }
  update_items<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/items/${encodeURIComponent(entity_id)}`, body);
  }
}

/** locations - pack-specific resource. */
export class LocationsResource extends BaseResource {
  create_locations<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/locations`, body);
  }
  delete_locations<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/locations/${encodeURIComponent(entity_id)}`);
  }
  get_locations<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/locations/${encodeURIComponent(entity_id)}`);
  }
  list_locations<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/locations`, params);
  }
  update_locations<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/locations/${encodeURIComponent(entity_id)}`, body);
  }
}

/** npcs - pack-specific resource. */
export class NpcsResource extends BaseResource {
  create_npcs<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/npcs`, body);
  }
  delete_npcs<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/npcs/${encodeURIComponent(entity_id)}`);
  }
  get_npcs<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/npcs/${encodeURIComponent(entity_id)}`);
  }
  list_npcs<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/npcs`, params);
  }
  update_npcs<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/npcs/${encodeURIComponent(entity_id)}`, body);
  }
}

/** places - pack-specific resource. */
export class PlacesResource extends BaseResource {
  create_places<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/places`, body);
  }
  delete_places<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/places/${encodeURIComponent(entity_id)}`);
  }
  get_places<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/places/${encodeURIComponent(entity_id)}`);
  }
  list_places<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/places`, params);
  }
  update_places<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/places/${encodeURIComponent(entity_id)}`, body);
  }
}

/** players - pack-specific resource. */
export class PlayersResource extends BaseResource {
  create_players<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/players`, body);
  }
  delete_players<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/players/${encodeURIComponent(entity_id)}`);
  }
  get_players<T = unknown>(project_id: string, entity_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/players/${encodeURIComponent(entity_id)}`);
  }
  list_players<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/players`, params);
  }
  update_players<T = unknown>(project_id: string, entity_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/players/${encodeURIComponent(entity_id)}`, body);
  }
}

/** seeds - pack-specific resource. */
export class SeedsResource extends BaseResource {
  batch_reject_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/batch/reject`, body);
  }
  batch_validate_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/batch/validate`, body);
  }
  delete_seed<T = unknown>(project_id: string, seed_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`);
  }
  generate_seeds<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/generate`, body);
  }
  get_seed<T = unknown>(project_id: string, seed_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`);
  }
  list_seeds<T = unknown>(project_id: string, params?: Record<string, string | number>): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds`, params);
  }
  patch_seed<T = unknown>(project_id: string, seed_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}`, body);
  }
  promote_seed<T = unknown>(project_id: string, seed_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/seeds/${encodeURIComponent(seed_id)}/promote`, body);
  }
}

/** sessions - pack-specific resource. */
export class SessionsResource extends BaseResource {
  create_snapshot<T = unknown>(session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/sessions/${encodeURIComponent(session_id)}/snapshot`, body);
  }
  get_session_status<T = unknown>(session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/sessions/${encodeURIComponent(session_id)}/status`);
  }
  hitl_respond<T = unknown>(session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/sessions/${encodeURIComponent(session_id)}/respond`, body);
  }
  stream_session_events<T = unknown>(session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/sessions/${encodeURIComponent(session_id)}/stream`);
  }
}

/** ttrpg - pack-specific resource. */
export class TtrpgResource extends BaseResource {
  check_journal_continuity<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/continuity/check`, body);
  }
  create_encounter<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters`, body);
  }
  create_note<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/notes`, body);
  }
  create_quest<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests`, body);
  }
  create_session<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions`, body);
  }
  delete_encounter<T = unknown>(project_id: string, encounter_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters/${encodeURIComponent(encounter_id)}`);
  }
  delete_note<T = unknown>(project_id: string, note_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/notes/${encodeURIComponent(note_id)}`);
  }
  delete_quest<T = unknown>(project_id: string, quest_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests/${encodeURIComponent(quest_id)}`);
  }
  delete_session<T = unknown>(project_id: string, session_id: string): Promise<T> {
    return this.http.delete<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions/${encodeURIComponent(session_id)}`);
  }
  generate_encounter<T = unknown>(project_id: string, encounter_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters/${encodeURIComponent(encounter_id)}/generate`, body);
  }
  generate_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests/${encodeURIComponent(quest_id)}/generate`, body);
  }
  generate_session<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions/${encodeURIComponent(session_id)}/generate`, body);
  }
  get_encounter<T = unknown>(project_id: string, encounter_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters/${encodeURIComponent(encounter_id)}`);
  }
  get_note<T = unknown>(project_id: string, note_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/notes/${encodeURIComponent(note_id)}`);
  }
  get_quest<T = unknown>(project_id: string, quest_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests/${encodeURIComponent(quest_id)}`);
  }
  get_session<T = unknown>(project_id: string, session_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions/${encodeURIComponent(session_id)}`);
  }
  import_vtt_commit<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/import/vtt/commit`, body);
  }
  import_vtt_route<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/import/vtt`, body);
  }
  list_encounters<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters`);
  }
  list_notes<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/notes`);
  }
  list_quests<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests`);
  }
  list_sessions<T = unknown>(project_id: string): Promise<T> {
    return this.http.get<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions`);
  }
  quick_dialogue<T = unknown>(project_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/quick-dialogue`, body);
  }
  refine_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.post<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests/${encodeURIComponent(quest_id)}/refine`, body);
  }
  update_encounter<T = unknown>(project_id: string, encounter_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/encounters/${encodeURIComponent(encounter_id)}`, body);
  }
  update_note<T = unknown>(project_id: string, note_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/notes/${encodeURIComponent(note_id)}`, body);
  }
  update_quest<T = unknown>(project_id: string, quest_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/quests/${encodeURIComponent(quest_id)}`, body);
  }
  update_session<T = unknown>(project_id: string, session_id: string, body: Record<string, unknown>): Promise<T> {
    return this.http.patch<T>(`/v1/projects/${encodeURIComponent(project_id)}/ttrpg-gm/sessions/${encodeURIComponent(session_id)}`, body);
  }
}
